In [7]:
import sys
!{sys.executable} -m pip install fastf1

Collecting fastf1
  Downloading fastf1-3.8.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from fastf1) (43.0.3)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (3.10.0)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.2.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from fastf1) (4.9.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.3)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.9.0.post0)
Collecting rapidfuzz (from fastf1)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Collecting requests-cache>=1.0.0 (from fastf1)
  Downloading requests_cache-1.3.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.32.4)
Requirement already satisfied: scipy<2.0.0,>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (1.16.3)
Collecting signalrcore (from fastf1)
  Downloading signalrcore-1.0.2-py3-none-any.whl.metadata (13 kB)
Collecting timple>=0.1.6 (from fastf1)
  Downloading timple-0.1.8-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: websockets>=10.3 in /usr/local/lib/python3.12/dist-packages (from fastf1) (15.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2026.4.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache>=1.0.0->fastf1) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache>=1.0.0->fastf1)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Collecting url-normalize>=2.0 (from requests-cache>=1.0.0->fastf1)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography->fastf1) (2.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.4.2)
Requirement already satisfied: msgpack==1.1.2 in /usr/local/lib/python3.12/dist-packages (from signalrcore->fastf1) (1.1.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography->fastf1) (3.0)
Downloading fastf1-3.8.3-py3-none-any.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.0/136.0 kB 3.9 MB/s eta 0:00:00
Downloading requests_cache-1.3.1-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 4.6 MB/s eta 0:00:00
Downloading timple-0.1.8-py3-none-any.whl (17 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 43.2 MB/s eta 0:00:0000:0100:01
Downloading signalrcore-1.0.2-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 3.4 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 4.6 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, signalrcore, rapidfuzz, cattrs, requests-cache, timple, fastf1
Successfully installed cattrs-26.1.0 fastf1-3.8.3 rapidfuzz-3.14.5 requests-cache-1.3.1 signalrcore-1.0.2 timple-0.1.8 url-normalize-3.0.0

In [8]:
import fastf1
import pandas as pd
import os

In [9]:
session = fastf1.get_session(2025,8,'Q')
session.name

req         WARNING 	DEFAULT CACHE ENABLED! (24.0 KB) /root/.cache/fastf1
WARNING:fastf1.fastf1.req:DEFAULT CACHE ENABLED! (24.0 KB) /root/.cache/fastf1

'Qualifying'

In [10]:
session.date

Timestamp('2025-05-24 14:00:00')

In [11]:
session.event

RoundNumber                                                      8
Country                                                     Monaco
Location                                                    Monaco
OfficialEventName    FORMULA 1 TAG HEUER GRAND PRIX DE MONACO 2025
EventDate                                      2025-05-25 00:00:00
EventName                                        Monaco Grand Prix
EventFormat                                           conventional
Session1                                                Practice 1
Session1Date                             2025-05-23 13:30:00+02:00
Session1DateUtc                                2025-05-23 11:30:00
Session2                                                Practice 2
Session2Date                             2025-05-23 17:00:00+02:00
Session2DateUtc                                2025-05-23 15:00:00
Session3                                                Practice 3
Session3Date                             2025-05-24 12:30:00+02:00
Session3DateUtc                                2025-05-24 10:30:00
Session4                                                Qualifying
Session4Date                             2025-05-24 16:00:00+02:00
Session4DateUtc                                2025-05-24 14:00:00
Session5                                                      Race
Session5Date                             2025-05-25 15:00:00+02:00
Session5DateUtc                                2025-05-25 13:00:00
F1ApiSupport                                                  True
Name: 8, dtype: object

In [15]:
scheduel = fastf1.get_event_schedule(2026)
print(scheduel)

    RoundNumber               Country           Location  \
0             0               Bahrain            Bahrain
1             0               Bahrain            Bahrain
2             1             Australia          Melbourne
3             2                 China           Shanghai
4             3                 Japan             Suzuka
5             4         United States      Miami Gardens
6             5                Canada           Montréal
7             6                Monaco        Monte Carlo
8             7                 Spain          Barcelona
9             8               Austria          Spielberg
10            9        United Kingdom        Silverstone
11           10               Belgium  Spa-Francorchamps
12           11               Hungary           Budapest
13           12           Netherlands          Zandvoort
14           13                 Italy              Monza
15           14                 Spain             Madrid
16           15            Azerbaijan               Baku
17           16             Singapore         Marina Bay
18           17         United States             Austin
19           18                Mexico        Mexico City
20           19                Brazil          São Paulo
21           20         United States          Las Vegas
22           21                 Qatar             Lusail
23           22  United Arab Emirates         Yas Marina

                                    OfficialEventName  EventDate  \
0          FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026 2026-02-13
1          FORMULA 1 ARAMCO PRE-SEASON TESTING 2 2026 2026-02-20
2   FORMULA 1 QATAR AIRWAYS AUSTRALIAN GRAND PRIX ... 2026-03-08
3          FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2026 2026-03-15
4           FORMULA 1 ARAMCO JAPANESE GRAND PRIX 2026 2026-03-29
5          FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2026 2026-05-03
6          FORMULA 1 LENOVO GRAND PRIX DU CANADA 2026 2026-05-24
7   FORMULA 1 LOUIS VUITTON GRAND PRIX DE MONACO 2026 2026-06-07
8   FORMULA 1 MSC CRUISES GRAN PREMIO DE BARCELONA... 2026-06-14
9           FORMULA 1 LENOVO AUSTRIAN GRAND PRIX 2026 2026-06-28
10          FORMULA 1 PIRELLI BRITISH GRAND PRIX 2026 2026-07-05
11   FORMULA 1 MOËT & CHANDON BELGIAN GRAND PRIX 2026 2026-07-19
12            FORMULA 1 AWS HUNGARIAN GRAND PRIX 2026 2026-07-26
13           FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2026 2026-08-23
14        FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2026 2026-09-06
15     FORMULA 1 TAG HEUER GRAN PREMIO DE ESPAÑA 2026 2026-09-13
16  FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX ... 2026-09-26
17  FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P... 2026-10-11
18  FORMULA 1 MSC CRUISES UNITED STATES GRAND PRIX... 2026-10-25
19  FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2026 2026-11-01
20  FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU... 2026-11-08
21       FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2026 2026-11-21
22      FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2026 2026-11-29
23  FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ... 2026-12-06

                   EventName        EventFormat    Session1  \
0         Pre-Season Testing            testing  Practice 1
1         Pre-Season Testing            testing  Practice 1
2      Australian Grand Prix       conventional  Practice 1
3         Chinese Grand Prix  sprint_qualifying  Practice 1
4        Japanese Grand Prix       conventional  Practice 1
5           Miami Grand Prix  sprint_qualifying  Practice 1
6        Canadian Grand Prix  sprint_qualifying  Practice 1
7          Monaco Grand Prix       conventional  Practice 1
8       Barcelona Grand Prix       conventional  Practice 1
9        Austrian Grand Prix       conventional  Practice 1
10        British Grand Prix  sprint_qualifying  Practice 1
11        Belgian Grand Prix       conventional  Practice 1
12      Hungarian Grand Prix       conventional  Practice 1
13          Dutch Grand Prix  sprint_qualifying  Practice 1
14        Italian Grand Prix       conventional  Practice 1
15        Spanish Grand Prix       conventional  Practice 1
16     Azerbaijan Grand Prix       conventional  Practice 1
17      Singapore Grand Prix  sprint_qualifying  Practice 1
18  United States Grand Prix       conventional  Practice 1
19    Mexico City Grand Prix       conventional  Practice 1
20      São Paulo Grand Prix       conventional  Practice 1
21      Las Vegas Grand Prix       conventional  Practice 1
22          Qatar Grand Prix       conventional  Practice 1
23      Abu Dhabi Grand Prix       conventional  Practice 1

                 Session1Date     Session1DateUtc  ...    Session3  \
0   2026-02-11 10:00:00+03:00 2026-02-11 07:00:00  ...  Practice 3
1   2026-02-18 10:00:00+03:00 2026-02-18 07:00:00  ...  Practice 3
2   2026-03-06 12:30:00+11:00 2026-03-06 01:30:00  ...  Practice 3
3   2026-03-13 11:30:00+08:00 2026-03-13 03:30:00  ...      Sprint
4   2026-03-27 11:30:00+09:00 2026-03-27 02:30:00  ...  Practice 3
5   2026-05-01 12:00:00-04:00 2026-05-01 16:00:00  ...      Sprint
6   2026-05-22 12:30:00-04:00 2026-05-22 16:30:00  ...      Sprint
7   2026-06-05 13:30:00+02:00 2026-06-05 11:30:00  ...  Practice 3
8   2026-06-12 13:30:00+02:00 2026-06-12 11:30:00  ...  Practice 3
9   2026-06-26 13:30:00+02:00 2026-06-26 11:30:00  ...  Practice 3
10  2026-07-03 12:30:00+01:00 2026-07-03 11:30:00  ...      Sprint
11  2026-07-17 13:30:00+02:00 2026-07-17 11:30:00  ...  Practice 3
12  2026-07-24 13:30:00+02:00 2026-07-24 11:30:00  ...  Practice 3
13  2026-08-21 12:30:00+02:00 2026-08-21 10:30:00  ...      Sprint
14  2026-09-04 12:30:00+02:00 2026-09-04 10:30:00  ...  Practice 3
15  2026-09-11 13:30:00+02:00 2026-09-11 11:30:00  ...  Practice 3
16  2026-09-24 12:30:00+04:00 2026-09-24 08:30:00  ...  Practice 3
17  2026-10-09 16:30:00+08:00 2026-10-09 08:30:00  ...      Sprint
18  2026-10-23 12:30:00-05:00 2026-10-23 17:30:00  ...  Practice 3
19  2026-10-30 12:30:00-06:00 2026-10-30 18:30:00  ...  Practice 3
20  2026-11-06 12:30:00-03:00 2026-11-06 15:30:00  ...  Practice 3
21  2026-11-19 16:30:00-08:00 2026-11-20 00:30:00  ...  Practice 3
22  2026-11-27 16:30:00+03:00 2026-11-27 13:30:00  ...  Practice 3
23  2026-12-04 13:30:00+04:00 2026-12-04 09:30:00  ...  Practice 3

                 Session3Date     Session3DateUtc    Session4  \
0   2026-02-13 10:00:00+03:00 2026-02-13 07:00:00        None
1   2026-02-20 10:00:00+03:00 2026-02-20 07:00:00        None
2   2026-03-07 12:30:00+11:00 2026-03-07 01:30:00  Qualifying
3   2026-03-14 11:00:00+08:00 2026-03-14 03:00:00  Qualifying
4   2026-03-28 11:30:00+09:00 2026-03-28 02:30:00  Qualifying
5   2026-05-02 12:00:00-04:00 2026-05-02 16:00:00  Qualifying
6   2026-05-23 12:00:00-04:00 2026-05-23 16:00:00  Qualifying
7   2026-06-06 12:30:00+02:00 2026-06-06 10:30:00  Qualifying
8   2026-06-13 12:30:00+02:00 2026-06-13 10:30:00  Qualifying
9   2026-06-27 12:30:00+02:00 2026-06-27 10:30:00  Qualifying
10  2026-07-04 12:00:00+01:00 2026-07-04 11:00:00  Qualifying
11  2026-07-18 12:30:00+02:00 2026-07-18 10:30:00  Qualifying
12  2026-07-25 12:30:00+02:00 2026-07-25 10:30:00  Qualifying
13  2026-08-22 12:00:00+02:00 2026-08-22 10:00:00  Qualifying
14  2026-09-05 12:30:00+02:00 2026-09-05 10:30:00  Qualifying
15  2026-09-12 12:30:00+02:00 2026-09-12 10:30:00  Qualifying
16  2026-09-25 12:30:00+04:00 2026-09-25 08:30:00  Qualifying
17  2026-10-10 17:00:00+08:00 2026-10-10 09:00:00  Qualifying
18  2026-10-24 12:30:00-05:00 2026-10-24 17:30:00  Qualifying
19  2026-10-31 11:30:00-06:00 2026-10-31 17:30:00  Qualifying
20  2026-11-07 11:30:00-03:00 2026-11-07 14:30:00  Qualifying
21  2026-11-20 16:30:00-08:00 2026-11-21 00:30:00  Qualifying
22  2026-11-28 17:30:00+03:00 2026-11-28 14:30:00  Qualifying
23  2026-12-05 14:30:00+04:00 2026-12-05 10:30:00  Qualifying

                 Session4Date     Session4DateUtc Session5  \
0                         NaT                 NaT     None
1                         NaT                 NaT     None
2   2026-03-07 16:00:00+11:00 2026-03-07 05:00:00     Race
3   2026-03-14 15:00:00+08:00 2026-03-14 07:00:00     Race
4   2026-03-28 15:00:00+09:00 2026-03-28 06:00:00     Race
5   2026-05-02 16:00:00-04:00 2026-05-02 20:00:00     Race
6   2026-05-23 16:00:00-04:00 2026-05-23 20:00:00     Race
7   2026-06-06 16:00:00+02:00 2026-06-06 14:00:00     Race
8   2026-06-13 16:00:00+02:00 2026-06-13 14:00:00     Race
9   2026-06-27 16:00:00+02:00 2026-06-27 14:00:00     Race
10  2026-07-04 16:00:00+01:00 2026-07-04 15:00:00     Race
11  2026-07-18 16:00:00+02:00 2026-07-18 14:00:00     Race
12  2026-07-25 16:00:00+02:00 2026-07-25 14:00:00     Race
13  2026-08-22 16:00:00+02:00 2026-08-22 14:00:00     Race
14  2026-09-05 16:00:00+02:00 2026-09-05 14:00:00     Race
15  2026-09-12 16:00:00+02:00 2026-09-12 14:00:00     Race
16  2026-09-25 16:00:00+04:00 2026-09-25 12:00:00     Race
17  2026-10-10 21:00:00+08:00 2026-10-10 13:00:00     Race
18  2026-10-24 16:00:00-05:00 2026-10-24 21:00:00     Race
19  2026-10-31 15:00:00-06:00 2026-10-31 21:00:00     Race
20  2026-11-07 15:00:00-03:00 2026-11-07 18:00:00     Race
21  2026-11-20 20:00:00-08:00 2026-11-21 04:00:00     Race
22  2026-11-28 21:00:00+03:00 2026-11-28 18:00:00     Race
23  2026-12-05 18:00:00+04:00 2026-12-05 14:00:00     Race

                 Session5Date     Session5DateUtc F1ApiSupport
0                         NaT                 NaT         True
1                         NaT                 NaT         True
2   2026-03-08 15:00:00+11:00 2026-03-08 04:00:00         True
3   2026-03-15 15:00:00+08:00 2026-03-15 07:00:00         True
4   2026-03-29 14:00:00+09:00 2026-03-29 05:00:00         True
5   2026-05-03 16:00:00-04:00 2026-05-03 20:00:00         True
6   2026-05-24 16:00:00-04:00 2026-05-24 20:00:00         True
7   2026-06-07 15:00:00+02:00 2026-06-07 13:00:00         True
8   2026-06-14 15:00:00+02:00 2026-06-14 13:00:00         True
9   2026-06-28 15:00:00+02:00 2026-06-28 13:00:00         True
10  2026-07-05 15:00:00+01:00 2026-07-05 14:00:00         True
11  2026-07-19 15:00:00+02:00 2026-07-19 13:00:00         True
12  2026-07-26 15:00:00+02:00 2026-07-26 13:00:00         True
13  2026-08-23 15:00:00+02:00 2026-08-23 13:00:00         True
14  2026-09-06 15:00:00+02:00 2026-09-06 13:00:00         True
15  2026-09-13 15:00:00+02:00 2026-09-13 13:00:00         True
16  2026-09-26 15:00:00+04:00 2026-09-26 11:00:00         True
17  2026-10-11 20:00:00+08:00 2026-10-11 12:00:00         True
18  2026-10-25 15:00:00-05:00 2026-10-25 20:00:00         True
19  2026-11-01 14:00:00-06:00 2026-11-01 20:00:00         True
20  2026-11-08 14:00:00-03:00 2026-11-08 17:00:00         True
21  2026-11-21 20:00:00-08:00 2026-11-22 04:00:00         True
22  2026-11-29 19:00:00+03:00 2026-11-29 16:00:00         True
23  2026-12-06 17:00:00+04:00 2026-12-06 13:00:00         True

[24 rows x 23 columns]

In [16]:
session.results

DataNotLoadedError: The data you are trying to access has not been loaded yet. See `Session.load`

In [17]:
session = fastf1.get_session(2025,8,'R')

In [ ]:
session.results

In [19]:
session.load()

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
INFO:fastf1.fastf1.core:Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
INFO:fastf1.api:Fetching session info data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
INFO:fastf1.api:Fetching driver list...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
INFO:fastf1.api:Fetching session status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
INFO:fastf1.fastf1.req:No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
INFO:fastf1.api:Fetching lap count data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
INFO:fastf1.api:Fetching track status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
INFO:fastf1.api:Fetching timing data...
_api           INFO 	Parsing timing data...
INFO:fastf1.api:Parsing timing data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
INFO:fastf1.api:Fetching timing app data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Processing timing data...
INFO:fastf1.fastf1.core:Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
INFO:fastf1.api:Fetching car data...
_api           INFO 	Parsing car data...
INFO:fastf1.api:Parsing car data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
INFO:fastf1.api:Fetching position data...
_api           INFO 	Parsing position data...
INFO:fastf1.api:Parsing position data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
INFO:fastf1.api:Fetching weather data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
INFO:fastf1.fastf1.req:No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
INFO:fastf1.api:Fetching race control messages...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']
INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']

In [20]:
session.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
4,4,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:40:33.843000,Finished,25.0,78.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:03.131000,Finished,18.0,78.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,3.0,3,3.0,NaT,NaT,NaT,0 days 00:00:03.658000,Finished,15.0,78.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,4.0,4,4.0,NaT,NaT,NaT,0 days 00:00:20.572000,Finished,12.0,78.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,5.0,5,7.0,NaT,NaT,NaT,0 days 00:00:51.387000,Finished,10.0,78.0
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6C98FF,rb,Isack,Hadjar,Isack Hadjar,...,6.0,6,5.0,NaT,NaT,NaT,0 days 00:01:05.082000,Lapped,8.0,77.0
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,7.0,7,8.0,NaT,NaT,NaT,0 days 00:01:06.029000,Lapped,6.0,77.0
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,8.0,8,9.0,NaT,NaT,NaT,0 days 00:01:06.746000,Lapped,4.0,77.0
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,9.0,9,10.0,NaT,NaT,NaT,0 days 00:00:11.869000,Lapped,2.0,76.0
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,10.0,10,11.0,NaT,NaT,NaT,0 days 00:00:15.232000,Lapped,1.0,76.0
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,11.0,11,14.0,NaT,NaT,NaT,0 days 00:00:33.844000,Lapped,0.0,76.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,12.0,12,20.0,NaT,NaT,NaT,0 days 00:00:54.693000,Lapped,0.0,76.0
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,13.0,13,18.0,NaT,NaT,NaT,0 days 00:00:57.114000,Lapped,0.0,76.0
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,01C00E,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,14.0,14,16.0,NaT,NaT,NaT,0 days 00:01:08.424000,Lapped,0.0,76.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,15.0,15,19.0,NaT,NaT,NaT,0 days 00:01:10.395000,Lapped,0.0,76.0
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,01C00E,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,16.0,16,13.0,NaT,NaT,NaT,0 days 00:01:11.544000,Lapped,0.0,76.0
22,22,Y TSUNODA,TSU,tsunoda,Red Bull Racing,4781D7,red_bull,Yuki,Tsunoda,Yuki Tsunoda,...,17.0,17,12.0,NaT,NaT,NaT,0 days 00:01:11.849000,Lapped,0.0,76.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,18.0,18,15.0,NaT,NaT,NaT,0 days 00:00:08.409000,Lapped,0.0,75.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,19.0,R,6.0,NaT,NaT,NaT,NaT,Retired,0.0,36.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,20.0,R,17.0,NaT,NaT,NaT,NaT,Retired,0.0,7.0

In [23]:
lap_info = session.laps
print(lap_info)

                       Time Driver DriverNumber                LapTime  \
0    0 days 00:57:36.090000    VER            1 0 days 00:01:27.020000
1    0 days 00:59:22.408000    VER            1 0 days 00:01:46.318000
2    0 days 01:01:11.223000    VER            1 0 days 00:01:48.815000
3    0 days 01:02:51.513000    VER            1 0 days 00:01:40.290000
4    0 days 01:04:12.313000    VER            1 0 days 00:01:20.800000
...                     ...    ...          ...                    ...
1420 0 days 02:32:33.863000    BEA           87 0 days 00:01:15.427000
1421 0 days 02:33:49.218000    BEA           87 0 days 00:01:15.355000
1422 0 days 02:35:04.583000    BEA           87 0 days 00:01:15.365000
1423 0 days 02:36:20.382000    BEA           87 0 days 00:01:15.799000
1424 0 days 02:37:37.606000    BEA           87 0 days 00:01:17.224000

      LapNumber  Stint PitOutTime PitInTime            Sector1Time  \
0           1.0    1.0        NaT       NaT                    NaT
1           2.0    1.0        NaT       NaT 0 days 00:00:34.949000
2           3.0    1.0        NaT       NaT 0 days 00:00:32.110000
3           4.0    1.0        NaT       NaT 0 days 00:00:31.006000
4           5.0    1.0        NaT       NaT 0 days 00:00:21.744000
...         ...    ...        ...       ...                    ...
1420       72.0    3.0        NaT       NaT 0 days 00:00:19.724000
1421       73.0    3.0        NaT       NaT 0 days 00:00:19.631000
1422       74.0    3.0        NaT       NaT 0 days 00:00:19.528000
1423       75.0    3.0        NaT       NaT 0 days 00:00:19.650000
1424       76.0    3.0        NaT       NaT 0 days 00:00:19.742000

                Sector2Time  ... FreshTyre             Team  \
0    0 days 00:00:38.394000  ...      True  Red Bull Racing
1    0 days 00:00:45.145000  ...      True  Red Bull Racing
2    0 days 00:00:47.430000  ...      True  Red Bull Racing
3    0 days 00:00:47.889000  ...      True  Red Bull Racing
4    0 days 00:00:37.485000  ...      True  Red Bull Racing
...                     ...  ...       ...              ...
1420 0 days 00:00:35.867000  ...      True     Haas F1 Team
1421 0 days 00:00:35.894000  ...      True     Haas F1 Team
1422 0 days 00:00:35.823000  ...      True     Haas F1 Team
1423 0 days 00:00:36.177000  ...      True     Haas F1 Team
1424 0 days 00:00:36.783000  ...      True     Haas F1 Team

               LapStartTime            LapStartDate  TrackStatus  Position  \
0    0 days 00:56:08.809000 2025-05-25 13:03:09.195           12       4.0
1    0 days 00:57:36.090000 2025-05-25 13:04:36.476           16       4.0
2    0 days 00:59:22.408000 2025-05-25 13:06:22.794            6       4.0
3    0 days 01:01:11.223000 2025-05-25 13:08:11.609          671       4.0
4    0 days 01:02:51.513000 2025-05-25 13:09:51.899            1       4.0
...                     ...                     ...          ...       ...
1420 0 days 02:31:18.436000 2025-05-25 14:38:18.822            1      13.0
1421 0 days 02:32:33.863000 2025-05-25 14:39:34.249            1      12.0
1422 0 days 02:33:49.218000 2025-05-25 14:40:49.604            1      12.0
1423 0 days 02:35:04.583000 2025-05-25 14:42:04.969            1      12.0
1424 0 days 02:36:20.382000 2025-05-25 14:43:20.768            1      12.0

      Deleted                    DeletedReason FastF1Generated IsAccurate
0       False                                            False      False
1       False                                            False      False
2       False                                            False      False
3       False                                            False      False
4       False                                            False       True
...       ...                              ...             ...        ...
1420    False                                            False       True
1421    False                                            False       True
1422    False                                            False       True
1423    False                                            False       True
1424     True  TRACK LIMITS AT TURN 10 LAP 76            False       True

[1425 rows x 31 columns]

In [30]:
df = lap_info[['DriverNumber','LapNumber','LapTime','Compound','TyreLife','Stint']]

In [25]:
print(df)

     DriverNumber  LapNumber                LapTime Compound  TyreLife  Stint
0               1        1.0 0 days 00:01:27.020000     HARD       1.0    1.0
1               1        2.0 0 days 00:01:46.318000     HARD       2.0    1.0
2               1        3.0 0 days 00:01:48.815000     HARD       3.0    1.0
3               1        4.0 0 days 00:01:40.290000     HARD       4.0    1.0
4               1        5.0 0 days 00:01:20.800000     HARD       5.0    1.0
...           ...        ...                    ...      ...       ...    ...
1420           87       72.0 0 days 00:01:15.427000   MEDIUM      55.0    3.0
1421           87       73.0 0 days 00:01:15.355000   MEDIUM      56.0    3.0
1422           87       74.0 0 days 00:01:15.365000   MEDIUM      57.0    3.0
1423           87       75.0 0 days 00:01:15.799000   MEDIUM      58.0    3.0
1424           87       76.0 0 days 00:01:17.224000   MEDIUM      59.0    3.0

[1425 rows x 6 columns]